version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-dependencies:
        applies-to: version-updates
        dependency-type: "all"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pip-dependencies:
        applies-to: version-updates
        dependency-type: "all"
        update-types:
          - "minor"
          - "patch"
